import Header from '@/components/shared/header';
import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import './globals.css';

const inter = Nunito({
	subsets: ['cyrillic'],
	variable: '--font-nunito',
	weight: ['400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<main className='min-h-screen'>
					<Header />
					{children}
				</main>
			</body>
		</html>
	);
}
